debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    blog: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  application.name: blog
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://blog.cnqmaeikg7ji.ap-northeast-2.rds.amazonaws.com:3306/blog
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      default_batch_fetch_size: 100
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        auto_quote_keyword: true

  thymeleaf3.decoupled-logic: true

server:
  port: 8090